sudo: required  
dist: xenial
language: node_js
node_js:
   - "9"
python:
  - "2.7"
notifications:
  email:
    onfailure: change
    onsuccess: change 
branches:
  only:
     - master
cache:
  directories:
    - "node_modules"  

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq  
  - sudo pip install ansible

install: 
  - npm install  
  - npm run build    
  - npm run deploy

 