sudo: required  
dist: xenial
language: node_js
node_js:
   - "9"
python:
  - "2.7"
notifications:
  email:
    onfailure: change
    onsuccess: change 
branches:
  only:
     - master
cache:
  directories:
    - "node_modules"  
env:
  ANSIBLE_HOST_KEY_CHECKING: false

before_install: 
  - sudo apt-get update -qq  
  - sudo pip install ansible

install: 
  - npm install  
  - npm run build    
  # - npm run deploy # needs ssh key config
 