sudo: required  
dist: xenial
language: node_js
node_js:
   - "9" 
notifications:
  email:
    onfailure: change
    onsuccess: change 
branches:
  only:
     - master
cache:
  directories:
    - "node_modules"   
install: 
  - npm install  
  - npm run build     
 