language: node_js
sudo: false
notifications:
  email:
    onfailure: change
    onsuccess: change 
branches:
  only:
     - master
cache:
  directories:
    - "node_modules"
node_js:
   - "9"
install:
  - npm install
script:
  - npm run build 