export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const DECREMENT_ITEM = "DECREMENT_ITEM";
export const INCREMENT_ITEM = "INCREMENT_ITEM";
export const CLEAR_CART = "CLEAR_CART";
export const SELECT_STORE = "SELECT_STORE";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_DRIVER_STATUS = "TOGGLE_DRIVER_STATUS";